networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge

services:
  # База данных Postgres
  postgres:
    image: postgres:12
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'banker_user'
      POSTGRES_PASSWORD: 'banker_mko123'
      POSTGRES_DB: 'simple_banker'
    ports:
      - '5432:5432'
    networks:
      - backend_network
  # Django Приложение
  backend:
    build:
      context: ./backend
      dockerfile: backend.dev.Dockerfile
    container_name: django
    volumes:
      # - ./backend:/app - bind mount лучше на production
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app
        # - action: sync+restart
        #   path: ./nginx/nginx.dev.conf
        #   target: /etc/nginx/conf.d/default.conf
    networks:
      - backend_network
      - frontend_network
  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: nginx.dev.Dockerfile
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - backend_network
  # Frontend Vue
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dev.Dockerfile
    container_name: vue
    # volumes:
    #   - ./frontend:/app
    ports:
      - '8080:8080'
    depends_on:
      - backend
    environment:
      - VUE_APP_REST_API_URL=http://localhost:80
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    networks:
      - frontend_network

volumes:
  postgres_data:
  static_volume:
  media_volume:
