# Generated by Django 5.0.6 on 2024-06-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(max_length=150, verbose_name='Подрядчик')),
                ('deal', models.CharField(max_length=150, verbose_name='Наименование сделки')),
                ('cost', models.FloatField(blank=True, default=0, verbose_name='Сумма сделки')),
                ('date', models.DateField(verbose_name='Дата сделки')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('done', 'Завершен'), ('canceled', 'Отменен'), ('pending', 'Выполняется')], max_length=20, verbose_name='Статус сделки')),
                ('date_log', models.DateTimeField(auto_now=True, verbose_name='Дата внесения изменений')),
                ('user_log', models.CharField(default='-', max_length=50, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'db_table': 'deals',
                'managed': True,
            },
        ),
    ]
