# Generated by Django 5.0.6 on 2024-07-07 17:29

import banker_api.api.pathes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banker_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to=banker_api.api.pathes.set_path_to_docs, verbose_name='Документы'),
        ),
    ]
