from .serializers import GroupsTokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView


class GroupsTokenObtainPairView(TokenObtainPairView):
  serializer_class = GroupsTokenObtainPairSerializer
